### ISSUE TITLE
Critical Outage of Game Servers Dallas TX

### ISSUE THREAD

**Issue by loopofficial** [Galaxy-Nexus-Hosting/incidents#4]
**We are experiencing a critical outage with our Dallas, TX game server. We are actively investigating this issue, and will update as more information becomes available.** [start_datetime:1723670400]  [end_datetime:1723694400]

**Comment by timmy-time** [comment]
All Services Restored. US-1 was successfully restarted and services started to become active again. Apologies for the inconvenience.
